name: rubocop
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: build
      run: |
        gem install bundler
        bin/setup
    - name: rspec
      run: bundle exec rspec
    - name: Run Rubocop
      run: bundle exec rubocop
